/**
 * Maple & Main Finds, wave 2: ten illustrated pins for every Draftpace
 * product, written the way a finds account talks ("found it", "POV",
 * "this is your sign") but promising only what each product really does.
 * Every product claim below traces to that product's Shop listing
 * (problemsSolved, inclusions, audience); prices are never typed here:
 * "{price}" and "{name}" are filled from the listing when the pin is
 * built, so a price change reaches every pin.
 *
 * Angles come from what people search for on Pinterest in each area
 * (small doable routines, micro money wins, printables and binders, ICE
 * binders, family health binders, homeschool portfolios, car care
 * checklists), and avoid what Maple & Main and Draftpace already posted.
 *
 * Layouts:
 *   scene  a big illustrated scene, the headline, then the fix and the product
 *   split  the problem on a dark half, the fix and the real screen on a light one
 *   list   a headline and three illustrated points
 *   pov    a POV line in a speech bubble over an illustrated scene
 *   board  a headline and four to six illustrated stickers, like a mood board
 */

export type FindsLayout = "scene" | "split" | "list" | "pov" | "board";

export type FindsPin = {
  product: string;
  layout: FindsLayout;
  /** The small label at the top, in finds lingo. */
  tag: string;
  /** The words on the pin, largest first. */
  head: string;
  /** The fix, one line. */
  sub: string;
  /** Illustrations for the scene, the first largest. */
  scene: string[];
  /** For list and board layouts: an illustration and a few words each. */
  points?: { motif: string; text: string }[];
  /** For the split layout: the product's own captured screen. */
  screen?: string;
  /** Pinterest title: the searched phrase first, 40 to 100 characters. */
  title: string;
  description: string;
  board: string;
  keywords: string[];
};

const P = (product: string, pins: Omit<FindsPin, "product">[]): FindsPin[] => pins.map((p) => ({ ...p, product }));

export const FINDS_PINS: FindsPin[] = [
  ...P("alongside", [
    {
      layout: "scene", tag: "Found it", scene: ["phone", "speech", "mind"],
      head: "For the phone call you've been avoiding for three weeks",
      sub: "It hands you an opening line and what to have in front of you. Then you dial.",
      title: "ADHD Phone Call Anxiety: Make the Call You Keep Avoiding",
      description: "This is your sign to finally make that call. The ADHD Life Companion gives you an opening line and a short list of what to have in front of you, then walks you through the hard part one question at a time. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["adhd phone anxiety", "adhd tips for adults", "executive dysfunction", "adhd life hacks"],
    },
    {
      layout: "split", tag: "Problem, meet fix", scene: ["checklist", "mind"], screen: "screens/alongside-workspace.png",
      head: "To-do lists just make me feel more behind",
      sub: "A screen that says nothing needs you right now, on the days that's true.",
      title: "ADHD Planner Alternative for When To-Do Lists Make It Worse",
      description: "If every to-do list turns into a longer list of things you're behind on, this one's different. It shows what deserves your attention from dates you set yourself, and says plainly when nothing needs you. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["adhd planner", "adhd to do list", "adhd organization", "adhd productivity"],
    },
    {
      layout: "list", tag: "Save this", scene: ["steps"],
      head: "3 ADHD-friendly ways to start when you're stuck",
      sub: "Small enough to do today.",
      points: [
        { motif: "steps", text: "Get help with one thing today, nothing to set up first" },
        { motif: "notebook", text: "Leave it half done. It remembers the exact question you stopped on" },
        { motif: "calendar", text: "Hear about it only on the date you set" },
      ],
      title: "ADHD Task Paralysis Tips: 3 Ways to Start When You're Stuck",
      description: "Task paralysis is real, and a bigger system is not the fix. The ADHD Life Companion helps with one thing today with nothing set up first, remembers exactly where you stopped, and stays out of the way until the date you chose. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["adhd task paralysis", "how to start tasks with adhd", "adhd tips", "executive function"],
    },
    {
      layout: "pov", tag: "Too real", scene: ["steps", "magnifier"],
      head: "POV: you put it down half finished and lost where you were",
      sub: "This one remembers the exact question you stopped on.",
      title: "ADHD Unfinished Projects: Pick Up Exactly Where You Left Off",
      description: "Coming back to a half finished thing costs more than starting it did. The ADHD Life Companion keeps a run you left half done and brings you back to the exact question, so picking it up isn't starting over. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["adhd unfinished projects", "adhd memory", "adhd hacks", "adhd organization tips"],
    },
    {
      layout: "board", tag: "Mood", scene: ["mind"],
      head: "What it holds, so your head doesn't have to",
      sub: "Write it down once. Hear about it when it matters.",
      points: [
        { motif: "phone", text: "The call you're dreading" },
        { motif: "mind", text: "The thing you keep meaning to do" },
        { motif: "calendar", text: "Dates you set yourself" },
        { motif: "people", text: "Someone who's gone quiet" },
        { motif: "notebook", text: "Where you left off" },
      ],
      title: "ADHD Brain Dump App: Everything You're Holding in One Place",
      description: "A brain dump that actually comes back to you at the right moment: a date you set, somebody who has gone quiet, a thread you left a fortnight ago. Write it once and stop carrying it. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["adhd brain dump", "adhd life admin", "adhd organization", "mental load"],
    },
    {
      layout: "scene", tag: "This is your sign", scene: ["notebook", "mind", "shield"],
      head: "A planner that never tells you that you failed",
      sub: "Just a record of what actually happened, in your own words.",
      title: "ADHD-Friendly Planner That Doesn't Make You Feel Like You Failed",
      description: "Every system eventually tells you that you failed at it. This one keeps a record of what actually happened, in your own words, and never once says you fell behind. For ADHD brains and anyone running on low executive function. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["adhd planner", "adhd friendly planner", "adhd shame", "gentle productivity"],
    },
    {
      layout: "split", tag: "For the foggy days", scene: ["mind", "steps"], screen: "screens/alongside-help.png",
      head: "Brain fog and a pile of life admin?",
      sub: "Help with one thing today, built for when holding a plan in your head has stopped working.",
      title: "Life Admin With Brain Fog: Long Covid, Grief, New Parenthood",
      description: "When brain fog from long covid, grief, new parenthood or illness makes life admin feel impossible, start with one thing. The ADHD Life Companion is built for the difficulty, not the diagnosis, and asks nothing about why. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["brain fog", "long covid brain fog", "life admin", "executive dysfunction"],
    },
    {
      layout: "list", tag: "Bookmark this", scene: ["speech"],
      head: "Scripts for the things that are hardest to start",
      sub: "Eight walk-throughs, one question at a time.",
      points: [
        { motif: "phone", text: "An opening line for the hard call" },
        { motif: "envelope", text: "The email you keep drafting in your head" },
        { motif: "steps", text: "One question on screen at a time" },
      ],
      title: "Scripts for Hard Phone Calls and Emails When You Have ADHD",
      description: "Suggested opening wording for the hardest calls and emails, and eight walk-throughs for the situations that are hardest to start. One question at a time, so the first step is never the whole task. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["phone call script", "adhd email", "adhd tips for adults", "procrastination help"],
    },
    {
      layout: "pov", tag: "Tell me without telling me", scene: ["mind", "phone"],
      head: "Tell me you have ADHD without telling me: same task on your mind for three weeks",
      sub: "It walks you through the hard version, one question at a time.",
      title: "ADHD Procrastination: When the Same Task Sits for Weeks",
      description: "Knowing exactly what to do and still not starting is not laziness. The ADHD Life Companion walks you through the hard version of it one question at a time, with the opening line ready. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["adhd procrastination", "executive dysfunction", "adhd memes", "adhd help"],
    },
    {
      layout: "board", tag: "Tried every planner?", scene: ["binder"],
      head: "For the brain that's tried every planner",
      sub: "No setup, no score, no catching up.",
      points: [
        { motif: "steps", text: "Helps before you set anything up" },
        { motif: "calendar", text: "Only what matters today" },
        { motif: "magnifier", text: "Back to exactly where you stopped" },
        { motif: "notebook", text: "Your own words, never a grade" },
      ],
      title: "Best Planner for ADHD Adults Who Gave Up on Planners",
      description: "If planners became one more thing to feel behind on, this is the find. No setup before it helps, only what deserves attention today, and a record in your own words that never grades you. Made by Draftpace. {name}, {price} once.",
      board: "ADHD Life Hacks", keywords: ["planner for adhd", "adhd adults", "adhd organization ideas", "adhd apps"],
    },
  ]),

  ...P("family-health-binder", [
    {
      layout: "scene", tag: "Mom hack", scene: ["document", "pills", "books"],
      head: "Stop rewriting the same answers on every school form",
      sub: "Allergies, meds, doctors and insurance, entered once. Print the Forms sheet.",
      title: "School Forms Hack: Every Health Answer in One Printable Sheet",
      description: "School, camp and sports forms ask the same health questions every year. Enter everyone's allergies, medications, doctors and insurance once in Family Health Binder, and print a Forms sheet in the order forms ask. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["school forms", "back to school organization", "mom hacks", "family medical binder"],
    },
    {
      layout: "split", tag: "Before date night", scene: ["people", "phone"], screen: "screens/family-health-binder-printables.png",
      head: "Leaving the kids with a sitter or grandparent?",
      sub: "A one-page Caregiver sheet: allergies first and largest, then who to call.",
      title: "Babysitter Info Sheet Printable: Allergies, Meds, Who to Call",
      description: "A text message is not enough when a sitter needs to know what to avoid. Print a Caregiver sheet with allergies first and largest, what's taken, who to call and your own notes about bedtime and comforts. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["babysitter information sheet", "babysitter printable", "grandparent info sheet", "mom life hacks"],
    },
    {
      layout: "list", tag: "Save this", scene: ["binder"],
      head: "5 printables every family health binder needs",
      sub: "All five print from what you entered once.",
      points: [
        { motif: "document", text: "Forms sheet, in the order forms ask" },
        { motif: "people", text: "Caregiver sheet for sitters" },
        { motif: "health", text: "Emergency card" },
        { motif: "doctor", text: "Visit page and intake summary" },
      ],
      title: "Family Medical Binder Printables: 5 Pages Every Family Needs",
      description: "The five pages that do the work: a Forms sheet, a Caregiver sheet, an Emergency card, a Visit page and an Intake summary, all on US Letter and all printed from what you entered once. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["family medical binder", "medical binder printables", "home organization printables", "family binder"],
    },
    {
      layout: "pov", tag: "Every parent ever", scene: ["clock", "doctor"],
      head: "POV: the intake desk asks exactly when the fever started",
      sub: "A symptom timeline with onset, duration and severity, logged as it happens.",
      title: "Kids Symptom Tracker: Answer the Doctor's Questions Fast",
      description: "No more reconstructing a symptom from memory under pressure. Family Health Binder keeps a symptom timeline per person with onset, duration and severity as real fields, recorded as it happens. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["symptom tracker", "kids health tracker", "sick kid tips", "pediatrician visit"],
    },
    {
      layout: "board", tag: "One place", scene: ["binder"],
      head: "Everything the forms ask, in one place",
      sub: "For every person in your family.",
      points: [
        { motif: "pills", text: "Medications" },
        { motif: "health", text: "Allergies" },
        { motif: "doctor", text: "Doctors" },
        { motif: "card", text: "Insurance" },
        { motif: "calendar", text: "Vaccines" },
        { motif: "phone", text: "Who to call" },
      ],
      title: "Family Health Information Organizer for Busy Parents",
      description: "Medications, allergies, doctors, insurance, vaccines and emergency contacts for everyone in the family, reachable from your phone instead of locked in one binder on a shelf. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["family health organizer", "medical information sheet", "family emergency binder", "mom organization"],
    },
    {
      layout: "scene", tag: "Save for your next appointment", scene: ["doctor", "checklist", "speech"],
      head: "The questions you meant to ask the doctor, written down",
      sub: "Print a Visit page with a box to tick for each one.",
      title: "Questions to Ask the Doctor: Printable Visit Page",
      description: "The questions vanish the second you sit down. Write them before the appointment, note what was said after, and print a Visit page with a box to tick for each question. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["doctor appointment checklist", "questions to ask doctor", "health binder", "appointment printable"],
    },
    {
      layout: "split", tag: "Small fix, big deal", scene: ["pills", "document"], screen: "screens/family-health-binder-members.png",
      head: "Old meds still on the list you hand over?",
      sub: "Mark it stopped. It leaves every printed page and stays in the record.",
      title: "Medication List Template That Stays Up to Date",
      description: "A medicine stopped in spring shouldn't still be on the list you hand over in fall. Mark it stopped and it leaves every printed page, stays in the record, and the list says when you last checked it. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["medication list", "medication tracker", "family health binder", "caregiver organization"],
    },
    {
      layout: "list", tag: "Sandwich generation", scene: ["people"],
      head: "Caring for your kids and your parent too?",
      sub: "One binder for all of them, no separate logins.",
      points: [
        { motif: "people", text: "A card per person, adults and kids alike" },
        { motif: "pills", text: "Each one's meds, doses and allergies" },
        { motif: "phone", text: "Doctors and who to call for each" },
      ],
      title: "Sandwich Generation Organization: Kids and Aging Parent Health",
      description: "When you're responsible for your kids and an aging parent, their facts can't all live in your head. One card per person, adults and children alike, including a parent you look after. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["sandwich generation", "caregiver organization", "aging parents", "family organization"],
    },
    {
      layout: "pov", tag: "Too real", scene: ["card", "suitcase"],
      head: "Me at camp check-in, trying to remember the insurance number",
      sub: "It's on the Forms sheet, in the order the form asks.",
      title: "Summer Camp Forms: Have Health Info and Insurance Ready",
      description: "Camp, school and sports forms every year, and the insurance number is never where you look. Keep it once in Family Health Binder and print it in the order forms ask. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["summer camp forms", "camp checklist", "mom hacks", "kids health records"],
    },
    {
      layout: "board", tag: "Privacy, sorted", scene: ["shield"],
      head: "Hand a stranger only what they need",
      sub: "A private choice on every record.",
      points: [
        { motif: "shield", text: "Mark any record private" },
        { motif: "document", text: "Left off every printout" },
        { motif: "checklist", text: "Each page says how many it left off" },
      ],
      title: "Family Health Records: Keep Private Details Off Printouts",
      description: "Not everything belongs on a page you hand to a stranger. Make any allergy, medication, symptom, vaccine or visit private, and every printed page leaves it off and says how many it left out. Made by Draftpace. {name}, {price} once.",
      board: "Family Organization Hacks", keywords: ["health records privacy", "family health binder", "medical organization", "mom organization tips"],
    },
  ]),

  ...P("home-management-companion", [
    {
      layout: "scene", tag: "New homeowner find", scene: ["house", "calendar", "toolbox"],
      head: "The home checklist that just tells you what's due this week",
      sub: "One sentence about this week. Then it stays out of the way.",
      title: "Home Maintenance Checklist App: What's Due This Week",
      description: "Not a dashboard to decode. Home Base answers one question in a sentence: does anything need you this week. The rest of the time it stays out of the way. Made by Draftpace. {name}, {price} once.",
      board: "Home Binder Ideas", keywords: ["home maintenance checklist", "new homeowner tips", "home organization", "house maintenance"],
    },
    {
      layout: "split", tag: "Broken or just due?", scene: ["toolbox", "calendar"], screen: "screens/home-management-companion-workspace.png",
      head: "Is it broken, or just due?",
      sub: "What's wrong right now, kept apart from what's merely due.",
      title: "Home Repair Tracker: Separate What's Broken From What's Due",
      description: "A dripping tap and an annual service are not the same kind of problem. Home Base keeps what's currently wrong separate from what's merely due, so the urgent thing never hides in a long list. Made by Draftpace. {name}, {price} once.",
      board: "Home Binder Ideas", keywords: ["home repair tracker", "house maintenance", "homeowner organization", "home binder"],
    },
    {
      layout: "list", tag: "For the reluctant homeowner", scene: ["house"],
      head: "Home maintenance for people who hate home maintenance",
      sub: "Tap, don't type.",
      points: [
        { motif: "house", text: "Tap what your home has, no typing" },
        { motif: "calendar", text: "Seasonal jobs in the month they belong" },
        { motif: "shield", text: "Reminders before it gets expensive" },
      ],
      title: "Easy Home Maintenance for People Who Hate Home Maintenance",
      description: "Set up by tapping instead of typing, get seasonal jobs in the month they actually belong, and hear about the expensive stuff before it turns into a repair. One hour of setup, then it remembers. Made by Draftpace. {name}, {price} once.",
      board: "Seasonal Home Care", keywords: ["home maintenance", "homeowner hacks", "house checklist", "seasonal home maintenance"],
    },
    {
      layout: "pov", tag: "We've all been there", scene: ["house", "water"],
      head: "POV: you remember the gutters in December",
      sub: "Seasonal jobs raised in the month they belong, before they're a repair.",
      title: "Seasonal Home Maintenance Reminders That Arrive on Time",
      description: "Seasonal work gets remembered a year too late. Home Base raises it in the month it belongs to, gutters, outside taps and all, before it becomes a repair bill. Made by Draftpace. {name}, {price} once.",
      board: "Seasonal Home Care", keywords: ["seasonal home maintenance", "gutter cleaning", "winter home prep", "home maintenance schedule"],
    },
    {
      layout: "board", tag: "One schedule", scene: ["house"],
      head: "122 kinds of thing, one care schedule",
      sub: "The boring, expensive jobs, caught early.",
      points: [
        { motif: "water", text: "Water heater" },
        { motif: "house", text: "Gutters" },
        { motif: "bulb", text: "Filters" },
        { motif: "toolbox", text: "Outside taps" },
      ],
      title: "Home Maintenance Schedule: 122 Kinds of Thing, Handled",
      description: "A hand-built care schedule covering 122 kinds of thing, seasonal jobs included. The water heater, the gutters, the filters and the outside tap before the first freeze, raised before they become repairs. Made by Draftpace. {name}, {price} once.",
      board: "Seasonal Home Care", keywords: ["home maintenance schedule", "water heater maintenance", "home care checklist", "homeowner checklist"],
    },
    {
      layout: "scene", tag: "First home?", scene: ["house", "checklist", "bulb"],
      head: "Start with twelve areas, not a 200-item list",
      sub: "Tap what your home has, from kitchen and laundry to the structure.",
      title: "First Time Homeowner Checklist: Start With 12 Areas",
      description: "First home and no idea what needs doing? Home Base splits a house into twelve areas, from kitchen and laundry to structure and renting. Tap what you have and it tells you what each one needs and roughly when. Made by Draftpace. {name}, {price} once.",
      board: "Home Binder Ideas", keywords: ["first time homeowner", "new home checklist", "homeowner tips", "home organization"],
    },
    {
      layout: "split", tag: "The forgotten one", scene: ["water", "calendar"], screen: "screens/home-management-companion-seasons.png",
      head: "That water heater you've never once thought about",
      sub: "The boring, expensive jobs raised before they're repairs.",
      title: "Water Heater Maintenance and the Jobs Homeowners Forget",
      description: "The expensive stuff gets caught too late, as a repair. Home Base raises the water heater, the gutters and the outside tap before they turn into a bill, then goes quiet again. Made by Draftpace. {name}, {price} once.",
      board: "Seasonal Home Care", keywords: ["water heater maintenance", "home maintenance tips", "homeowner hacks", "house care"],
    },
    {
      layout: "list", tag: "Room by room", scene: ["house"],
      head: "Room by room: what your house needs and when",
      sub: "Tap what you have. It fills in the rest.",
      points: [
        { motif: "bulb", text: "Kitchen and laundry" },
        { motif: "water", text: "Water and plumbing" },
        { motif: "house", text: "Roof and structure" },
      ],
      title: "Room by Room Home Maintenance Checklist for Homeowners",
      description: "Room-by-room beats a giant list. Tap what your home has across twelve areas and Home Base tells you what each one needs and roughly when, before anything becomes a repair. Made by Draftpace. {name}, {price} once.",
      board: "Home Binder Ideas", keywords: ["room by room checklist", "home maintenance", "cleaning and maintenance", "house organization"],
    },
    {
      layout: "pov", tag: "Real talk", scene: ["mind", "house"],
      head: "Me pretending I know how often the furnace needs a service",
      sub: "A care schedule that knows, and raises it in the right month.",
      title: "How Often to Service Your Furnace and Other Home Systems",
      description: "Most homeowners are guessing. Home Base comes with a care schedule for 122 kinds of thing and raises each job in the month it belongs to, so you stop guessing and start knowing. Made by Draftpace. {name}, {price} once.",
      board: "Seasonal Home Care", keywords: ["furnace maintenance", "hvac maintenance", "home maintenance schedule", "homeowner tips"],
    },
    {
      layout: "board", tag: "Only when it matters", scene: ["house"],
      head: "A home app that only speaks up when something's due",
      sub: "Then it goes back to minding its business.",
      points: [
        { motif: "calendar", text: "Due this week" },
        { motif: "toolbox", text: "What's wrong right now" },
        { motif: "house", text: "Twelve areas of your home" },
        { motif: "shield", text: "Reminders before it's costly" },
      ],
      title: "Home Organization App for Homeowners Who Hate Notifications",
      description: "No endless dashboard. Home Base says what's due this week, keeps what's wrong right now separate, and reminds you before something becomes expensive. On quiet weeks it says so. Made by Draftpace. {name}, {price} once.",
      board: "Home Binder Ideas", keywords: ["home organization app", "home maintenance app", "homeowner organization", "home binder ideas"],
    },
  ]),

  ...P("homeschooling-companion", [
    {
      layout: "scene", tag: "Homeschool mom find", scene: ["notebook", "books", "calendar"],
      head: "Homeschool records that keep up with you",
      sub: "Log what you actually did, as it happens. Hand it over at year's end.",
      title: "Easy Homeschool Record Keeping You'll Actually Keep Up With",
      description: "Homeschool records shouldn't be a second job. Log what you actually did as it happens, on paper or on screen, and print a record per child you could hand to somebody at year's end. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool record keeping", "homeschool organization", "homeschool mom", "homeschool portfolio"],
    },
    {
      layout: "split", tag: "Every March", scene: ["calendar", "mind"], screen: "screens/homeschooling-companion-record.png",
      head: "By March, can you remember what you covered in October?",
      sub: "A record of what you actually did, kept as it happened.",
      title: "Homeschool Log: Remember What You Covered All Year",
      description: "Mid-year memory is not a record. Homeschooling Companion keeps what you actually did as it happened, so March you can answer October's questions. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool log", "homeschool planner", "homeschool records", "homeschool tips"],
    },
    {
      layout: "list", tag: "Print these", scene: ["notebook"],
      head: "Homeschool planner pages for the whole year",
      sub: "Undated, so they work whenever you start.",
      points: [
        { motif: "calendar", text: "Year planner and weekly plan" },
        { motif: "notebook", text: "Daily log and subject record" },
        { motif: "books", text: "Reading log and days schooled" },
      ],
      title: "Homeschool Planner Printables: Year, Week, Day, Reading Log",
      description: "Undated working pages for the whole year: year planner, weekly plan, daily log, subject record, reading log and days schooled, in a 30 page book you can print as often as you like. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool planner printable", "homeschool reading log", "homeschool printables", "homeschool planning"],
    },
    {
      layout: "pov", tag: "Multi-kid life", scene: ["people", "books"],
      head: "POV: three kids, three curriculums, one kitchen table",
      sub: "One page each morning that says what today looks like, per child.",
      title: "Homeschooling Multiple Kids: One Daily Page per Child",
      description: "Keeping several children's records straight in your head stops working fast. Homeschooling Companion gives each child their own curriculum, subjects and plan, and one page each morning per child. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschooling multiple kids", "homeschool schedule", "homeschool mom life", "homeschool organization"],
    },
    {
      layout: "board", tag: "What's inside", scene: ["books"],
      head: "Inside the 30 page Homeschool Year book",
      sub: "Yours to keep and print.",
      points: [
        { motif: "books", text: "Six chapters of method" },
        { motif: "notebook", text: "Undated working pages" },
        { motif: "checklist", text: "Six check sheets" },
        { motif: "document", text: "Answer key at the back" },
      ],
      title: "Homeschool Handbook Printable: Method, Pages and Check Sheets",
      description: "A 30 page printed book: six chapters of method on running a week and what to record, undated working pages, and six check sheets of eight questions with the answer key kept at the back. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool printables", "homeschool handbook", "homeschool binder", "homeschool resources"],
    },
    {
      layout: "scene", tag: "Save for evaluation season", scene: ["document", "magnifier", "books"],
      head: "Know what your state asks you to keep, before someone checks",
      sub: "Your state's requirements, line by line, against what you've recorded.",
      title: "Homeschool Requirements by State: See What You're Missing",
      description: "Not sure what your state actually asks you to keep? Homeschooling Companion sets your state's record keeping requirements beside what you've recorded, on the printed record, so you see the gap first. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool requirements by state", "homeschool laws", "homeschool evaluation", "homeschool records"],
    },
    {
      layout: "split", tag: "Did it stick?", scene: ["checklist", "books"], screen: "screens/homeschooling-companion-kids.png",
      head: "Did it actually stick?",
      sub: "Short checks per topic, including the answer 'not enough evidence to say'.",
      title: "How to Know If Your Homeschooler Actually Learned It",
      description: "Covered is not learned. Short checks of eight questions per topic, reported one topic at a time, including the answer that there isn't enough evidence to say yet. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool assessment", "homeschool tips", "learning check", "homeschool curriculum"],
    },
    {
      layout: "list", tag: "No exam hall vibes", scene: ["books"],
      head: "Check learning without turning the table into an exam hall",
      sub: "Eight questions, marked by you.",
      points: [
        { motif: "speech", text: "Eight questions per check" },
        { motif: "books", text: "71 curriculum-neutral topics" },
        { motif: "checklist", text: "Answer key kept out of sight" },
      ],
      title: "Gentle Homeschool Assessment Ideas: No Tests Needed",
      description: "Want to know whether something landed without making it feel like a test? Six printable check sheets of eight questions, 71 curriculum-neutral topics, and the answer key kept at the back where the child can't read it. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool assessment ideas", "gentle homeschooling", "homeschool printables", "homeschool learning"],
    },
    {
      layout: "pov", tag: "Paper or screen", scene: ["notebook", "laptop"],
      head: "Paper some weeks, screen other weeks. Both count.",
      sub: "A printed book that works with a pencil, and an app when you want it.",
      title: "Homeschool Planner That Works on Paper and on Screen",
      description: "Some weeks you want a pencil, some weeks a screen. The Homeschool Year book keeps working on paper whether or not you open the app, and the app keeps the record when you do. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool planner", "paper planner", "homeschool organization ideas", "homeschool mom"],
    },
    {
      layout: "board", tag: "Your curriculum, your call", scene: ["books"],
      head: "Keeps up with the curriculum you chose",
      sub: "It follows you. It doesn't replace you.",
      points: [
        { motif: "books", text: "Follows your curriculum" },
        { motif: "people", text: "Unlimited children" },
        { motif: "document", text: "A printed record per child" },
        { motif: "shield", text: "Only what you choose to include" },
      ],
      title: "Homeschool Tracker That Works With Any Curriculum",
      description: "You chose your curriculum on purpose. Homeschooling Companion follows it, for as many children as you teach, and prints a record per child with only what you chose to include. Made by Draftpace. {name}, {price} once.",
      board: "Homeschool Organization", keywords: ["homeschool tracker", "any curriculum", "homeschool portfolio", "homeschool organization"],
    },
  ]),

  ...P("monthly-money-reset", [
    {
      layout: "scene", tag: "Free find", scene: ["wallet", "calendar", "shield"],
      head: "How much can I actually spend this month? One number.",
      sub: "Your bills held back first, updated as the month goes on.",
      title: "How Much Can I Spend This Month? A Free Safe to Spend Number",
      description: "Skip the mental math. Monthly Money Reset gives you one Safe-to-Spend figure that holds your bills back first and updates as the month goes on. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["budgeting for beginners", "safe to spend", "money tips", "budget app free"],
    },
    {
      layout: "split", tag: "Rent says otherwise", scene: ["bank", "receipt"], screen: "screens/monthly-money-reset-progress.png",
      head: "The balance looks fine. The bill coming Friday says otherwise.",
      sub: "Protected bills stay held back, paid or not.",
      title: "Available Balance vs Bills: See What's Really Yours to Spend",
      description: "A bill you haven't paid yet still feels like money you have. In Monthly Money Reset, protected bills stay held back whether they're paid or not, so the number never counts money you owe. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["budgeting tips", "paycheck to paycheck", "bill tracker", "money management"],
    },
    {
      layout: "list", tag: "Hate budgeting?", scene: ["wallet"],
      head: "A budget for people who hate budgeting",
      sub: "No categories to keep up with.",
      points: [
        { motif: "wallet", text: "One number, nothing to categorise" },
        { motif: "calendar", text: "A short weekly check-in" },
        { motif: "steps", text: "A way back in after weeks away" },
      ],
      title: "Budget for People Who Hate Budgeting: One Number, Free",
      description: "Tried every budget and quit? This isn't one. One number for what's safe to spend, a short weekly check-in, and a way back in after weeks away with no overdue pile-up. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["budget for beginners", "simple budget", "budgeting tips", "money saving tips"],
    },
    {
      layout: "pov", tag: "Every month", scene: ["calendar", "chart"],
      head: "POV: the month looks fine until the 23rd",
      sub: "It names your tightest day and how low you'd get, ahead of time.",
      title: "Find Your Tightest Day of the Month Before It Happens",
      description: "The month can look fine on average and still go wrong on one day. Monthly Money Reset names the tightest day this cycle and the amount you'd be down to, worked out from dates you already entered. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["paycheck to paycheck", "money tips", "budget planning", "cash flow"],
    },
    {
      layout: "board", tag: "Micro money wins", scene: ["piggy"],
      head: "Small money wins for this month",
      sub: "Four small moves, one free app.",
      points: [
        { motif: "wallet", text: "Know your safe-to-spend" },
        { motif: "shield", text: "Protect the bills first" },
        { motif: "calendar", text: "Spot your tightest day" },
        { motif: "checklist", text: "Close the month, carry it forward" },
      ],
      title: "Small Money Wins: A Free Monthly Money Reset",
      description: "Small, doable money wins: know what's safe to spend, protect the bills first, spot the tightest day before it hits, and close the month with the balance carried into the next. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["money reset", "monthly reset", "money challenge", "budgeting ideas"],
    },
    {
      layout: "scene", tag: "Bookmark this", scene: ["calendar", "wallet", "clock"],
      head: "Paycheck to paycheck? Find your tightest day first",
      sub: "Worked out from the bill and income dates you already entered.",
      title: "Paycheck to Paycheck Budgeting: Find Your Tightest Day",
      description: "When money is tight, the average month doesn't matter. The tightest day does. Monthly Money Reset shows it beside your Safe-to-Spend number whenever your balance dips before it recovers. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["paycheck to paycheck budget", "budgeting for beginners", "money tips", "low income budget"],
    },
    {
      layout: "split", tag: "Again?", scene: ["steps", "wallet"], screen: "screens/monthly-money-reset-progress.png",
      head: "Fell off budgeting by month two? Again?",
      sub: "No overdue pile-up waiting. Just a way back in.",
      title: "How to Restart Budgeting After You Fell Off",
      description: "Most budgets get abandoned by month two because catching up feels worse than starting. Monthly Money Reset has a short weekly check-in and a way back in after weeks away, with no pile-up waiting. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["budget restart", "budgeting tips", "money reset", "financial fresh start"],
    },
    {
      layout: "list", tag: "Five minutes", scene: ["checklist"],
      head: "What a five minute money check-in looks like",
      sub: "Once a week. That's it.",
      points: [
        { motif: "wallet", text: "Any income in, or changed?" },
        { motif: "receipt", text: "Any bill changed, or paid?" },
        { motif: "card", text: "Spending you haven't added?" },
      ],
      title: "Weekly Money Check-In: A 5 Minute Budget Routine",
      description: "A weekly money routine small enough to keep: any income in or changed, any bill changed or paid, any spending you haven't added. Monthly Money Reset keeps the number right in between. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["weekly money routine", "budget check in", "money habits", "budgeting for beginners"],
    },
    {
      layout: "pov", tag: "Too real", scene: ["wallet", "mind"],
      head: "Me doing mental math in the checkout line",
      sub: "Or: one number that already did it.",
      title: "Stop Doing Mental Math: Know What's Safe to Spend",
      description: "No more adding it up in your head at the register. Monthly Money Reset keeps one Safe-to-Spend number that updates as the month goes on, with every figure behind it a tap away. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["money tips", "spending tracker", "budgeting hacks", "frugal living"],
    },
    {
      layout: "board", tag: "Not a whole system", scene: ["wallet"],
      head: "A money app that isn't a whole budget system",
      sub: "Free, and small on purpose.",
      points: [
        { motif: "wallet", text: "Safe-to-Spend" },
        { motif: "calendar", text: "Weekly check-ins" },
        { motif: "chart", text: "Tightest day" },
        { motif: "bulb", text: "Your next useful move" },
      ],
      title: "Free Money App for Beginners That Isn't a Full Budget",
      description: "Want one clear number, not a full budget system? Safe-to-Spend, weekly check-ins, your tightest day and a next useful move, all from a few numbers a month. {price} to use. Made by Draftpace.",
      board: "Budgeting for Beginners", keywords: ["free budget app", "budgeting for beginners", "money management tips", "personal finance tips"],
    },
  ]),

  ...P("personal-finance-companion", [
    {
      layout: "scene", tag: "Money organization find", scene: ["laptop", "wallet", "chart"],
      head: "All your money in one place, not five apps",
      sub: "Accounts, bills, subscriptions, debt and savings, always current.",
      title: "Organize Your Finances: All Your Money in One Place",
      description: "Bank apps, statements, memory and habit: that's not a system. Personal Finance Companion keeps accounts, income, bills, subscriptions, transactions, debt and savings in one current picture. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["organize finances", "financial organization", "money tracker", "personal finance tips"],
    },
    {
      layout: "split", tag: "Debt-free when?", scene: ["chart", "calendar"], screen: "screens/personal-finance-companion-debt.png",
      head: "When will this debt actually be gone?",
      sub: "A payoff plan from your own balances and rates, with the month you're debt-free.",
      title: "Debt Payoff Plan: See the Month You'll Be Debt Free",
      description: "Stop guessing. Personal Finance Companion builds a payoff plan from your own balances, rates and minimum payments: the month you're debt-free and the order your debts clear. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["debt payoff plan", "debt free journey", "pay off debt", "debt tracker"],
    },
    {
      layout: "list", tag: "Snowball or avalanche?", scene: ["chart"],
      head: "Debt snowball vs avalanche, worked out for you",
      sub: "On your real numbers, not an example.",
      points: [
        { motif: "chart", text: "Smallest balance or highest rate first" },
        { motif: "calendar", text: "Your debt-free month, either way" },
        { motif: "piggy", text: "What the cheaper order saves" },
      ],
      title: "Debt Snowball vs Avalanche Calculator on Your Own Numbers",
      description: "Snowball or avalanche? See both on your own balances, rates and minimums, with an extra amount you choose: the debt-free month either way and what the cheaper method saves. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["debt snowball", "debt avalanche", "debt payoff", "debt free tips"],
    },
    {
      layout: "pov", tag: "Did I though?", scene: ["checklist", "receipt"],
      head: "POV: did I pay the water bill, or just think about it?",
      sub: "Tick it paid. What's left to pay works itself out.",
      title: "Monthly Bill Tracker: See What You've Paid at a Glance",
      description: "Can't remember which bills you've paid this month? Tick a bill paid and Personal Finance Companion works out what's left to pay from what you ticked. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["bill tracker", "monthly bills", "bill payment checklist", "money organization"],
    },
    {
      layout: "board", tag: "Couples and roommates", scene: ["people"],
      head: "Splitting bills with a partner or roommate?",
      sub: "No more 'wait, did I pay you back?'",
      points: [
        { motif: "people", text: "Your share of each bill" },
        { motif: "checklist", text: "Tick it settled" },
        { motif: "document", text: "A statement of what's owed" },
      ],
      title: "How to Split Bills With a Partner or Roommate Fairly",
      description: "Mark a bill or subscription shared, set your share, and tick it settled when it really is. A generated statement says what's settled and what's still owed. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["split bills", "couples finances", "roommate bills", "shared expenses"],
    },
    {
      layout: "scene", tag: "Save this", scene: ["calendar", "receipt", "wallet"],
      head: "What does a normal month really cost you?",
      sub: "A typical month written out from what you recorded, like a budget planner.",
      title: "Monthly Budget Planner: What a Normal Month Really Costs",
      description: "What comes in, what goes out, what's set aside for each goal and what's left, written out from what you recorded. Anything it couldn't count is named underneath. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["monthly budget", "budget planner", "monthly expenses", "budgeting tips"],
    },
    {
      layout: "split", tag: "Stop re-typing", scene: ["laptop", "receipt"], screen: "screens/personal-finance-companion-records.png",
      head: "Still re-typing your bank statement by hand?",
      sub: "Import a CSV or paste notes, review what changed, then confirm.",
      title: "Import Bank Statement CSV Into Your Budget, No Retyping",
      description: "Reviewing a statement shouldn't mean typing it all again. Import a bank statement, a note or a CSV and review what changed before anything joins your picture. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["bank statement csv", "budget spreadsheet", "expense tracker", "money organization"],
    },
    {
      layout: "list", tag: "Only real flags", scene: ["magnifier"],
      head: "A money tracker that only flags real problems",
      sub: "From your own records. Never made up.",
      points: [
        { motif: "magnifier", text: "Gaps in your own records" },
        { motif: "shield", text: "Never a made-up task" },
        { motif: "bulb", text: "One useful next move" },
      ],
      title: "Money Tracker That Flags Problems Before They Cost You",
      description: "Find out something's off before it's a problem. A real Attention inbox shows only real gaps in your own records, never a task invented to look busy, plus one useful next move. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["money tracker", "financial organization", "budgeting app", "personal finance"],
    },
    {
      layout: "pov", tag: "Found one", scene: ["card", "magnifier"],
      head: "Me finding a subscription I forgot I had",
      sub: "Subscriptions with amounts and renewal dates, and a missing date flagged.",
      title: "Subscription Tracker: Find the Ones You Forgot About",
      description: "Subscriptions get their own area with amounts and renewal dates, and a missing renewal date shows up in Attention instead of being ignored. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["subscription tracker", "cancel subscriptions", "save money tips", "money saving"],
    },
    {
      layout: "board", tag: "One picture", scene: ["wallet"],
      head: "Every money area, one picture",
      sub: "Always current, never a guess.",
      points: [
        { motif: "bank", text: "Accounts" },
        { motif: "wallet", text: "Income" },
        { motif: "receipt", text: "Bills" },
        { motif: "card", text: "Subscriptions" },
        { motif: "chart", text: "Debt" },
        { motif: "piggy", text: "Savings" },
      ],
      title: "Personal Finance Organizer: Accounts, Bills, Debt, Savings",
      description: "Accounts, income, bills, subscriptions, transactions, debt and savings in one place, with a breakdown of how every figure was worked out one tap away. Made by Draftpace. {name}, {price} once.",
      board: "Money Organization Tips", keywords: ["personal finance organizer", "financial planner", "money organization", "finance binder"],
    },
  ]),

  ...P("personal-life-affairs-companion", [
    {
      layout: "scene", tag: "Adulting find", scene: ["binder", "speech", "people"],
      head: "The 'if something happens to me' file, one question at a time",
      sub: "105 questions, and only the ones that apply to you.",
      title: "If Something Happens to Me File: Done One Question at a Time",
      description: "The file everyone means to make. Personal Life Affairs Companion asks one question at a time, only where it applies to you, and prints a book you can hand over when you're ready. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["if something happens to me", "in case of emergency binder", "life admin", "adulting"],
    },
    {
      layout: "split", tag: "Would they know?", scene: ["document", "people"], screen: "screens/personal-life-affairs-companion-workspace.png",
      head: "Would anyone know where your will is?",
      sub: "Where the will is, who decides, who to call: raised first.",
      title: "In Case of Emergency Binder: Start With What Matters Most",
      description: "The things that cost the most to leave undone come first: who decides, who to call, where the will is, and who's named on the forms that override it. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["in case of emergency binder", "where is my will", "estate planning organization", "family binder"],
    },
    {
      layout: "list", tag: "Start here", scene: ["binder"],
      head: "ICE binder: the three things that matter most",
      sub: "Before the folder of everything.",
      points: [
        { motif: "document", text: "Where the will is" },
        { motif: "people", text: "Who decides, and who to call" },
        { motif: "bank", text: "Who's named on the forms that override it" },
      ],
      title: "ICE Binder Checklist: The 3 Things to Write Down First",
      description: "An in case of emergency binder doesn't start with every account. It starts with where the will is, who decides, who to call, and who's named on the beneficiary forms. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["ice binder", "emergency binder checklist", "estate planning", "life binder"],
    },
    {
      layout: "pov", tag: "Six years later", scene: ["steps", "binder"],
      head: "POV: you've meant to sort this out for six years",
      sub: "One small question on screen at a time, chosen for you.",
      title: "Getting Your Affairs in Order When You Don't Know Where to Start",
      description: "Never found a first step small enough to take? This asks one question at a time, chosen for you, instead of handing you a blank folder to organise yourself. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["get affairs in order", "life admin", "adulting checklist", "estate planning tips"],
    },
    {
      layout: "board", tag: "The book", scene: ["binder"],
      head: "Print a book your family can actually use",
      sub: "In your words, most urgent first.",
      points: [
        { motif: "binder", text: "Opens on 'if you need to'" },
        { motif: "notebook", text: "In your own words" },
        { motif: "checklist", text: "Most urgent first" },
        { motif: "people", text: "Usable without a login" },
      ],
      title: "Printable Life Binder Your Family Can Use Without a Login",
      description: "My Affairs is a printable book in your own words. It opens on what somebody would be trying to do first, so a person who has never used the app could pick it up and use it. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["life binder printable", "family emergency binder", "what to do when i die binder", "legacy binder"],
    },
    {
      layout: "scene", tag: "Save this for later", scene: ["document", "bank", "scale"],
      head: "Your beneficiary forms can override your will",
      sub: "It asks who's named on yours, early.",
      title: "Beneficiary vs Will: Why Your Forms May Override Your Will",
      description: "A pension, 401(k) or life policy often goes to whoever is named on the form, not your will. Personal Life Affairs Companion raises who's named on yours as one of the first things it asks. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["beneficiary vs will", "estate planning", "life insurance tips", "401k beneficiary"],
    },
    {
      layout: "split", tag: "Still true?", scene: ["calendar", "document"], screen: "screens/personal-life-affairs-companion-affairs.png",
      head: "Wrote it all down once, years ago?",
      sub: "It comes back and asks whether it's still true.",
      title: "Keep Your Emergency Binder Up to Date Without Starting Over",
      description: "Things written down once stop being true. Entries come back for a second look on their own schedule, and every change is kept, so you can still see what it used to say. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["update emergency binder", "life admin", "estate planning organization", "family binder"],
    },
    {
      layout: "list", tag: "Life happens", scene: ["calendar"],
      head: "Life changes that make your paperwork wrong",
      sub: "Nine life events, each bringing forward what it changed.",
      points: [
        { motif: "house", text: "Moving house" },
        { motif: "people", text: "Separating" },
        { motif: "document", text: "Someone you named has died" },
      ],
      title: "Life Changes That Mean You Should Update Your Paperwork",
      description: "Moving, separating, or losing someone you named: each life event brings forward exactly what it made untrue, so your affairs stay right after things change. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["life changes paperwork", "update will", "life admin checklist", "adulting"],
    },
    {
      layout: "pov", tag: "Real question", scene: ["people", "checklist"],
      head: "Could someone else actually handle it if they had to?",
      sub: "A handoff check, scenario by scenario.",
      title: "Could Your Family Manage Your Affairs? A Handoff Check",
      description: "Not 'how much have you finished' but 'could somebody else manage'. A handoff check answers scenario by scenario, by what someone would be trying to do, and names the one thing worth fixing first. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["family emergency plan", "estate planning", "what to do when someone dies", "life admin"],
    },
    {
      layout: "board", tag: "Only what's yours", scene: ["binder"],
      head: "A life admin binder minus the pages that aren't you",
      sub: "A simpler life makes a shorter binder.",
      points: [
        { motif: "binder", text: "Only what applies to you" },
        { motif: "checklist", text: "46 things, in order" },
        { motif: "calendar", text: "Second looks on a schedule" },
        { motif: "document", text: "Every change kept" },
      ],
      title: "Life Admin Binder That Skips Everything That Doesn't Apply",
      description: "Half of what a binder makes you fill in has nothing to do with your life. Here, everything that doesn't apply is absent entirely. 46 things in order, across eight areas of life. Made by Draftpace. {name}, {price} once.",
      board: "Life Admin and Emergency Binder", keywords: ["life admin binder", "life binder", "home organization binder", "adulting tips"],
    },
  ]),

  ...P("travel-companion", [
    {
      layout: "scene", tag: "Travel planner find", scene: ["plane", "route", "clock"],
      head: "Flight moved? See everything else it affects",
      sub: "The transfer, the check-in, the dinner booked around it, one at a time.",
      title: "Flight Changed? See Everything Else It Affects in Your Trip",
      description: "When a flight moves, the real problem is everything booked around it. Record the change and Travel Companion walks through the transfer, the check-in and the reservation that depended on it. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["travel planning", "flight delay tips", "trip planner", "travel hacks"],
    },
    {
      layout: "split", tag: "Six inboxes?", scene: ["envelope", "ticket"], screen: "screens/travel-companion-workspace.png",
      head: "Confirmation numbers in six different inboxes?",
      sub: "The reference and the provider, readable in three seconds.",
      title: "Travel Organization: Every Confirmation Number in One Place",
      description: "When the desk asks for the confirmation number, it's in one of six inboxes and a screenshot. Travel Companion keeps what you booked, who it's for and what it depends on in one place. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["travel organization", "travel documents organizer", "trip planning", "travel tips"],
    },
    {
      layout: "list", tag: "For the group planner", scene: ["people"],
      head: "Group trip planning for the friend who plans everything",
      sub: "You, but with backup.",
      points: [
        { motif: "people", text: "Who's travelling and what they need" },
        { motif: "ticket", text: "What each booking depends on" },
        { motif: "suitcase", text: "Packing lists per traveller" },
      ],
      title: "Group Trip Planning Tips for the Friend Who Plans Everything",
      description: "Always the one everybody asks? Keep who's travelling, their requirements and documents, what each booking depends on, and packing lists per traveller in one place. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["group trip planning", "family vacation planning", "travel planner", "trip organization"],
    },
    {
      layout: "pov", tag: "4% battery", scene: ["phone", "document"],
      head: "POV: phone at 4% in a taxi and the whole plan is on it",
      sub: "A printed trip book, so the plan isn't on one phone.",
      title: "Printable Trip Planner So Your Plans Aren't Only on Your Phone",
      description: "Your phone dies, the plan goes with it. Travel Companion prints a trip book you can carry, so the trip never depends on one device staying charged. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["printable travel planner", "travel binder", "trip itinerary", "travel tips"],
    },
    {
      layout: "board", tag: "No spreadsheet", scene: ["route"],
      head: "Multi-stop trip, zero spreadsheets",
      sub: "The shape of your trip, held for you.",
      points: [
        { motif: "route", text: "Day by day itinerary" },
        { motif: "ticket", text: "Bookings and what they hang on" },
        { motif: "document", text: "Documents and where they're kept" },
        { motif: "suitcase", text: "Starter packing lists" },
      ],
      title: "Multi-Stop Trip Planner Without a Spreadsheet",
      description: "Destinations, bookings, travellers and documents in one place, the whole trip laid out day by day, and starter packing lists by trip type. No spreadsheet to maintain. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["multi stop trip", "itinerary template", "road trip planner", "europe trip planning"],
    },
    {
      layout: "scene", tag: "Bookmark for your next trip", scene: ["clock", "plane", "route"],
      head: "Crossing time zones? Today means today where you are",
      sub: "Every place carries its real time zone, daylight saving included.",
      title: "Time Zone Travel Tips: Never Mix Up Your Dates Again",
      description: "A booking crosses a time zone and suddenly you're not sure it's still today. Each place in Travel Companion carries its real time zone, so today means today where you actually are. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["time zone travel", "international travel tips", "travel hacks", "trip planning"],
    },
    {
      layout: "split", tag: "One-way for now", scene: ["plane", "calendar"], screen: "screens/travel-companion-itinerary.png",
      head: "Haven't booked your flight home yet?",
      sub: "Add your visa's expiry and it holds a placeholder return date.",
      title: "One Way Trip Planning When You Don't Have a Return Date",
      description: "Every planner wants a return date you don't have yet. For a trip abroad, add your visa's expiry once and Travel Companion fills a placeholder return date until you book the real flight. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["one way trip", "long term travel", "travel planning tips", "digital nomad"],
    },
    {
      layout: "list", tag: "When travel goes wrong", scene: ["plane"],
      head: "When travel goes sideways, you're not winging it",
      sub: "Walk-throughs for the worst moments.",
      points: [
        { motif: "plane", text: "From a flight change" },
        { motif: "key", text: "To something lost or stolen" },
        { motif: "speech", text: "Plus the replies you're waiting on" },
      ],
      title: "What to Do When Travel Goes Wrong: Step by Step",
      description: "Nine walk-throughs for when something goes wrong, from a flight change to something lost or stolen, plus open threads for anything you're still waiting to hear back on. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["travel emergency", "flight cancelled what to do", "lost passport", "travel tips"],
    },
    {
      layout: "pov", tag: "The designated planner", scene: ["people", "clock"],
      head: "POV: you're the one everybody asks what time we leave",
      sub: "Today's plan on one screen, for the whole group.",
      title: "Family Trip Organization: Today's Plan on One Screen",
      description: "Tired of being the group's itinerary? Travel Companion shows today's state of the trip on one screen, and on days the trip needs nothing from you, it says so. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["family trip planning", "group travel", "vacation itinerary", "travel organization"],
    },
    {
      layout: "board", tag: "Next time", scene: ["notebook"],
      head: "Remember what you learned the last time you went",
      sub: "Your trips, kept and printable.",
      points: [
        { motif: "notebook", text: "A dated record of what happened" },
        { motif: "bulb", text: "What to know before next time" },
        { motif: "binder", text: "Past trips stay printable" },
      ],
      title: "Travel Journal Ideas: Remember What to Know Next Time",
      description: "Going back to the same place a year later and forgetting everything you learned? Keep a dated record of what happened and what's worth knowing next time. Finished trips stay readable and printable. Made by Draftpace. {name}, {price} once.",
      board: "Travel Planning Tips", keywords: ["travel journal", "travel memories", "trip record", "travel planning"],
    },
  ]),

  ...P("vehicle-maintenance-companion", [
    {
      layout: "scene", tag: "Car care find", scene: ["car", "notebook", "wrench"],
      head: "Write down the interval the mechanic quoted. Once.",
      sub: "Kept against that car, editable, for good.",
      title: "Car Maintenance Tracker: Keep the Interval Your Mechanic Quoted",
      description: "The exact interval you were quoted for your specific car is easy to forget. Type it once in Vehicle Maintenance Companion and it stays against that vehicle for good, editable any time. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["car maintenance tracker", "car maintenance schedule", "oil change reminder", "car care tips"],
    },
    {
      layout: "split", tag: "Shop counter season", scene: ["wrench", "receipt"], screen: "screens/vehicle-maintenance-companion-printables.png",
      head: "\"While we had it up on the lift...\"",
      sub: "A dated Service Boundary: what's requested today, and what isn't authorized.",
      title: "Avoid Surprise Car Repair Bills: Put Your Request in Writing",
      description: "A routine visit turns into a much bigger bill. Print a dated, mileage-stamped Service Boundary that says what you're requesting today and that nothing else is authorized without a conversation. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["car repair tips", "mechanic tips", "car maintenance", "save money on car repairs"],
    },
    {
      layout: "list", tag: "Used car, no records?", scene: ["car"],
      head: "Bought a used car with no service history?",
      sub: "Start the record from today.",
      points: [
        { motif: "magnifier", text: "Unknown history: nothing assumed done" },
        { motif: "notebook", text: "Log each real fact as you learn it" },
        { motif: "wrench", text: "Usual jobs for its age and use" },
      ],
      title: "Used Car With No Service Records: What to Do First",
      description: "A used or inherited car with no history to check? Mark its history unknown and nothing is assumed done or overdue until you record a real fact. Usual jobs are suggested from fuel, age, mileage and use. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["used car tips", "buying a used car", "car maintenance checklist", "car care"],
    },
    {
      layout: "pov", tag: "Every shop visit", scene: ["car", "receipt"],
      head: "POV: the shop asks your mileage at the last oil change",
      sub: "Every service kept with its day, mileage, shop and cost.",
      title: "Car Service History Log: Mileage, Date and Cost Every Time",
      description: "Every service you record is kept with its day, mileage, who did it and what it cost, organised by year, so the next shop question has an answer. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["car service log", "oil change log", "car maintenance log", "vehicle records"],
    },
    {
      layout: "board", tag: "Selling soon?", scene: ["car"],
      head: "Selling your car? Show it was looked after",
      sub: "A printable service record, in your own hand.",
      points: [
        { motif: "receipt", text: "Every service, dated" },
        { motif: "car", text: "Mileage at each one" },
        { motif: "wrench", text: "Who did it" },
        { motif: "document", text: "A printable record for the buyer" },
      ],
      title: "Selling Your Car: How to Show Its Service History",
      description: "No proof the car was looked after when it's time to sell? Every service you record prints as a service record that says plainly it's your own, with dates, mileage, who did it and cost. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["selling a car tips", "car service history", "car resale value", "car maintenance records"],
    },
    {
      layout: "scene", tag: "No fake urgency", scene: ["car", "shield", "calendar"],
      head: "A car app that doesn't cry wolf",
      sub: "What's due, ranked. And 'nothing is due' when nothing is.",
      title: "Car Maintenance App Without the Fake Urgency",
      description: "Most maintenance apps become a list of manufactured urgency you stop opening. This one is a single ranked screen of what's actually due, no score, and a plain 'nothing is due' when that's true. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["car maintenance app", "car care", "vehicle maintenance", "car care for beginners"],
    },
    {
      layout: "split", tag: "Tow or short trips?", scene: ["car", "clock"], screen: "screens/vehicle-maintenance-companion-vehicles.png",
      head: "Towing, short trips, heat or dust?",
      sub: "A severe-duty switch halves only the interval you entered, job by job.",
      title: "Severe Driving Conditions: Adjust Your Car Maintenance Intervals",
      description: "Towing or short-trip driving shortens some intervals, not all. Turn on severe duty for one job and it halves only the interval you actually entered, changeable any time. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["severe driving conditions", "oil change interval", "car maintenance tips", "towing tips"],
    },
    {
      layout: "list", tag: "Don't speak mechanic?", scene: ["wrench"],
      head: "Car care for people who don't speak mechanic",
      sub: "Your manual wins. Always.",
      points: [
        { motif: "wrench", text: "Typical starting intervals, labelled typical" },
        { motif: "notebook", text: "Every one editable to your manual" },
        { motif: "calendar", text: "Due when it's actually due" },
      ],
      title: "Car Maintenance for Beginners Who Don't Speak Mechanic",
      description: "Not a car person? Start from a short list of typical intervals, always labelled typical and always editable, and change any of them to what your manual says. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["car maintenance for beginners", "car tips", "first car", "car care checklist"],
    },
    {
      layout: "pov", tag: "Whose number wins?", scene: ["car", "scale"],
      head: "POV: the dealer says it's due. Your manual says it isn't.",
      sub: "Your number wins here. Every interval stays editable.",
      title: "Dealer vs Owner's Manual: Which Maintenance Schedule to Follow",
      description: "Enter the interval you actually believe and it's kept against that car. Nothing here overrides your number with its own. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["car maintenance schedule", "dealer maintenance", "owners manual", "car tips"],
    },
    {
      layout: "board", tag: "One tidy place", scene: ["car"],
      head: "Everything about your car, in one tidy place",
      sub: "For every vehicle you own.",
      points: [
        { motif: "car", text: "Every vehicle" },
        { motif: "wrench", text: "Service history" },
        { motif: "document", text: "Paperwork dates" },
        { motif: "shield", text: "Service Boundary" },
        { motif: "receipt", text: "Costs by year" },
      ],
      title: "Car Organization: Service History, Paperwork and Costs",
      description: "Service history by year, paperwork dates, a Service Boundary for the shop and costs over time, for as many vehicles as you own. Made by Draftpace. {name}, {price} once.",
      board: "Car Care Tips", keywords: ["car organization", "car binder", "vehicle records", "car maintenance"],
    },
  ]),
];
