import { Blobatar } from "@blobatar/react";

/**
 * A deterministic, per-account avatar — the one place a signed-in user's
 * identity renders as a compact control, reused by AccountMenu across the
 * authenticated app and both public-header states. Generated by Blobatar
 * (github.com/Alain00/blobatar, MIT), not uploaded: the same seed always
 * renders the same blobatar, so every account gets a distinct image for
 * free the moment it's created, with nothing to store but a string.
 *
 * `seed` is the identity that decides the image — pass the account's own
 * `avatar_seed` once they've picked one, falling back to their user id
 * (resolveAvatarSeed in product-framework/avatarSeed.ts does exactly
 * this) — never the display name or email, both of which can change
 * without the person asking for a new-looking avatar. `label` is
 * decorative only, the accessible name for the image.
 */
const SIZE_PX = { sm: 32, md: 40 } as const;
const SIZE_CLASS = { sm: "h-8 w-8", md: "h-10 w-10" } as const;

export default function Avatar({
  label,
  seed,
  size = "md",
  className = "",
}: {
  /** Display name or email, used only as the accessible name, never for generation. */
  label: string;
  /** The stable identity Blobatar hashes into an image. Falls back to `label` if omitted. */
  seed?: string;
  size?: keyof typeof SIZE_CLASS;
  className?: string;
}) {
  return (
    <Blobatar
      name={seed || label}
      alt={label}
      size={SIZE_PX[size]}
      background="circle"
      className={`shrink-0 rounded-full ${SIZE_CLASS[size]} ${className}`}
    />
  );
}
