#!/usr/bin/env node
/**
 * Runs the director over director/slate.json: for every brief, analyses
 * the placement and product, plans a unique film and writes
 *
 *   shots/<product>/films/<platform>--<goal>.film.json   the frame-exact script the Film composition renders
 *   shots/<product>/films/<platform>--<goal>.md          the treatment: analysis, decisions and the script, for review
 *   shots/guides/<guide>/<platform>.film.json / .md      the same, for a guide-driven film
 *   src/films.generated.ts                                every film, for Root.tsx
 *
 *   node scripts/direct.mjs            plan the whole slate
 *   node scripts/direct.mjs travel     ...and print only briefs matching "travel"
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { createServer } from "vite";

const filter = process.argv[2];
const vite = await createServer({
  configFile: false, logLevel: "error", appType: "custom",
  server: { middlewareMode: true }, optimizeDeps: { noDiscovery: true },
  resolve: { alias: { "@": path.resolve("../src") } },
});
const { runSlate } = await vite.ssrLoadModule(path.resolve("director/run.ts"));
const { filmPath } = await vite.ssrLoadModule(path.resolve("director/film.ts"));
const results = runSlate();
await vite.close();

const imports = [];
for (const [i, { film, doc }] of results.entries()) {
  const base = path.join("shots", filmPath(film));
  await mkdir(path.dirname(base), { recursive: true });
  await writeFile(`${base}.film.json`, JSON.stringify(film, null, 2) + "\n");
  await writeFile(`${base}.md`, doc + "\n");
  imports.push({ name: `f${i}`, file: `../${base}.film.json` });
  if (!filter || film.id.includes(filter)) console.log(`${film.id.padEnd(60)} ${film.structure.padEnd(12)} ${(film.durationInFrames / 30).toFixed(1)}s  "${film.angle.text.slice(0, 60)}"`);
}
await writeFile("src/films.generated.ts",
  `// Generated by scripts/direct.mjs from director/slate.json. Do not edit.\nimport type { Film } from "../director/film";\n` +
  imports.map((x) => `import ${x.name} from "${x.file}";`).join("\n") +
  `\n\nexport const FILMS = [${imports.map((x) => x.name).join(", ")}] as unknown as Film[];\n`);
console.log(`${results.length} films planned`);
process.exit(0);
