#!/usr/bin/env node
// One-time generator: reads the real Newsreader/IBM Plex Sans files already
// used elsewhere in this repo (public/fonts/ at the project root, the same
// files scripts/pinterest-maple-main/pastel.mjs uses) and writes them as
// base64 data-URI @font-face rules. Inlined, not staticFile()'d: a data URI
// is resolved synchronously by the CSS parser, no network fetch, no
// document.fonts.ready race — the thing that hung the render twice before
// (see SKILL.md trap #6) was specifically an async load, not these fonts
// themselves.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT_FONTS = path.resolve(process.cwd(), "../public/fonts");
const OUT = path.resolve(process.cwd(), "src/fonts-inline.css");

async function dataUri(file) {
  const buf = await readFile(path.join(ROOT_FONTS, file));
  return `data:font/ttf;base64,${buf.toString("base64")}`;
}

const newsreader = await dataUri("Newsreader.ttf");
const plexSans = await dataUri("IBMPlexSans.ttf");

await writeFile(
  OUT,
  `/* Generated by scripts/inline-fonts.mjs from ../public/fonts/*.ttf. Do not hand-edit. */\n` +
    `@font-face { font-family: "Newsreader"; font-weight: 400 700; font-style: normal; src: url("${newsreader}") format("truetype"); }\n` +
    `@font-face { font-family: "IBM Plex Sans"; font-weight: 400 700; font-style: normal; src: url("${plexSans}") format("truetype"); }\n`
);
console.log(`wrote ${OUT}`);
