// Generated by scripts/voiceover.mjs from voiceover/. Do not edit.
import type { Film } from "../director/film";
import v0 from "../shots/voiceover/safe-to-spend-explainer/youtube-short.film.json";

export const VOICEOVER_FILMS = [v0] as unknown as Film[];
