/**
 * Writing planned films to disk: the one place that knows the layout of
 * shots/ and the generated film lists. scripts/direct.mjs,
 * scripts/voiceover.mjs and Draftpace Studio all write through here, so a
 * film saved from Studio is byte for byte what the command line writes.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { filmPath, type Film } from "./film";

/**
 * The creative/ folder. A bundler may rewrite `new URL(..., import.meta.url)`
 * into an asset import, so the path is built from this file's own path, and
 * a host that bundles the engine elsewhere (Studio) can name it outright.
 */
export const CREATIVE_DIR = process.env.DRAFTPACE_CREATIVE_DIR ?? path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function writeList(file: string, exportName: string, comment: string, films: Film[]) {
  const imports = films.map((f, i) => ({ name: `${exportName === "FILMS" ? "f" : "v"}${i}`, file: `../shots/${filmPath(f)}.film.json` }));
  fs.writeFileSync(path.join(CREATIVE_DIR, file),
    `// ${comment} Do not edit.\nimport type { Film } from "../director/film";\n` +
    imports.map((x) => `import ${x.name} from "${x.file}";`).join("\n") +
    `${imports.length ? "\n" : ""}\nexport const ${exportName} = [${imports.map((x) => x.name).join(", ")}] as unknown as Film[];\n`);
}

function writeFilm(film: Film, doc: string) {
  const base = path.join(CREATIVE_DIR, "shots", filmPath(film));
  fs.mkdirSync(path.dirname(base), { recursive: true });
  fs.writeFileSync(`${base}.film.json`, JSON.stringify(film, null, 2) + "\n");
  fs.writeFileSync(`${base}.md`, doc + "\n");
}

/** Every film the director planned (slate.json), and src/films.generated.ts. Films no longer planned are removed, so nothing stale lingers. */
export function writeDirected(results: { film: Film; doc: string }[]) {
  const shots = path.join(CREATIVE_DIR, "shots");
  for (const dir of ["guides", "situations"]) fs.rmSync(path.join(shots, dir), { recursive: true, force: true });
  for (const product of fs.readdirSync(shots)) fs.rmSync(path.join(shots, product, "films"), { recursive: true, force: true });
  for (const { film, doc } of results) writeFilm(film, doc);
  writeList("src/films.generated.ts", "FILMS", "Generated by scripts/direct.mjs from director/slate.json.", results.map((r) => r.film));
}

/** Every voice-over film, replacing shots/voiceover/ wholesale so a deleted voice-over leaves nothing behind. */
export function writeVoiceovers(results: { film: Film; doc: string }[]) {
  fs.rmSync(path.join(CREATIVE_DIR, "shots", "voiceover"), { recursive: true, force: true });
  for (const { film, doc } of results) writeFilm(film, doc);
  writeList("src/voiceover-films.generated.ts", "VOICEOVER_FILMS", "Generated by scripts/voiceover.mjs from voiceover/.", results.map((r) => r.film));
}

/** Every situation carousel (director/carousel.ts) as shots/carousels/<product>/<moment>.carousel.json, and src/carousels.generated.ts. */
export function writeCarousels(carousels: import("./carousel").Carousel[]) {
  const dir = path.join(CREATIVE_DIR, "shots", "carousels");
  fs.rmSync(dir, { recursive: true, force: true });
  const files = carousels.map((car, i) => {
    const rel = `${car.product}/${car.id.replace(`car-${car.product}-`, "")}.carousel.json`;
    fs.mkdirSync(path.join(dir, car.product), { recursive: true });
    fs.writeFileSync(path.join(dir, rel), JSON.stringify(car, null, 2) + "\n");
    return { name: `c${i}`, file: `../shots/carousels/${rel}` };
  });
  fs.writeFileSync(path.join(CREATIVE_DIR, "src/carousels.generated.ts"),
    `// Generated by scripts/carousels.mjs from director/carousel.ts. Do not edit.\nimport type { Carousel } from "../director/carousel";\n` +
    files.map((x) => `import ${x.name} from "${x.file}";`).join("\n") +
    `\n\nexport const CAROUSELS = [${files.map((x) => x.name).join(", ")}] as unknown as Carousel[];\n`);
}
